/**
 * Real-sales metric tiles: total revenue (CA) and total margin actually
 * generated by the products picked up so far in the running session, plus
 * their per-second rates.
 *
 * Unlike `absoluteYield.ts` (potential yield of the *exposed* assortment,
 * regardless of whether it was ever picked up), these figures only count
 * real pickups, mirroring `yieldMetrics.ts` for the tile display pattern.
 * Pure functions so they can be unit-tested; consumed by the
 * « Waypoints & rendement » panel tiles.
 */
import type { CADProduct } from '../types/cad';
import type { PickedProductSample } from '../store/simulationStore';
import { productMarginEur } from './marginHeatmap';

export interface SalesStats {
  /** Elapsed simulated time (s) the rates are averaged over. */
  elapsedSeconds: number;
  /** Σ price de vente (€) des produits réellement pris. */
  totalCaEur: number;
  /** Σ marge (€) des produits réellement pris. */
  totalMarginEur: number;
  /** Chiffre d'affaires par seconde (€/s). */
  caPerSecond: number;
  /** Marge par seconde (€/s). */
  marginPerSecond: number;
}

/** Identifier of one sales metric tile. */
export type SalesMetricId = 'ca-total' | 'margin-total' | 'margin-per-second' | 'ca-per-second';

/** Order in which the metric tiles are rendered. */
export const SALES_METRIC_IDS: SalesMetricId[] = [
  'ca-total',
  'margin-total',
  'margin-per-second',
  'ca-per-second',
];

/**
 * Aggregate every pickup recorded so far into totals and per-second rates.
 * Returns `null` when there is no elapsed simulated time yet, so callers can
 * skip the tiles instead of plotting zeros.
 */
export function computeSalesStats(
  log: PickedProductSample[] | null | undefined,
  products: CADProduct[],
  elapsedSeconds: number,
): SalesStats | null {
  if (!Number.isFinite(elapsedSeconds) || elapsedSeconds <= 0) return null;

  const productByEan = new Map<string, CADProduct>();
  for (const product of products) productByEan.set(product.ean, product);

  let totalCaEur = 0;
  let totalMarginEur = 0;
  for (const sample of log ?? []) {
    const product = productByEan.get(sample.ean);
    if (!product) continue;
    totalCaEur += product.priceSellEur ?? 0;
    totalMarginEur += productMarginEur(product);
  }

  return {
    elapsedSeconds,
    totalCaEur,
    totalMarginEur,
    caPerSecond: totalCaEur / elapsedSeconds,
    marginPerSecond: totalMarginEur / elapsedSeconds,
  };
}

function formatFr(value: number, digits: number): string {
  if (!Number.isFinite(value)) return '—';
  return value.toLocaleString('fr-FR', { maximumFractionDigits: digits });
}

/** Short label + formatted value of one metric, shared by tiles. */
export function salesMetricDisplay(
  id: SalesMetricId,
  stats: SalesStats | null,
): { label: string; value: string } {
  switch (id) {
    case 'ca-total':
      return { label: 'CA total', value: stats ? `${formatFr(stats.totalCaEur, 0)} €` : '—' };
    case 'margin-total':
      return { label: 'Marge total', value: stats ? `${formatFr(stats.totalMarginEur, 0)} €` : '—' };
    case 'margin-per-second':
      return { label: 'Marge/s', value: stats ? `${formatFr(stats.marginPerSecond, 2)} €/s` : '—' };
    case 'ca-per-second':
      return { label: 'CA/s', value: stats ? `${formatFr(stats.caPerSecond, 2)} €/s` : '—' };
  }
}
